module.exports={
	"DEVICE_NOT_INITIALIZED_ERROR_CODE":"EZETAP_323020",
	"DEVICE_NOT_INITIALIZED_ERROR_MSG":"Device not initialized, call INITIALIZE API.",
	"MANDATORY_PARAMETER_ERROR_CODE":"EZETAP_323023",
	"MANDATORY_PARAMETER_ERROR_MSG":"Mandatory parameters are missing.",
	"SEND_RECEIPT_ERROR_CODE":"EZETAP_323025",
	"SEND_RECEIPT_ERROR_MSG":"Exception occurred in SEND RECEIPT API",
	"TAKE_PAYEMENT_ERROR_CODE":"EZETAP_323026",
	"TAKE_PAYEMENT_ERROR_MSG":"Exception occurred in TAKE PAYMENT API.",
	"TRANSACTION_DETAIL_ERROR_CODE":"EZETAP_323028",
	"TRANSACTION_DETAIL_ERROR_MSG":"Exception occurred in TRANACTION DETAIL API.",
	"VOID_TRANSACTION_ERROR_CODE":"EZETAP_323029",
	"VOID_TRANSACTION_ERROR_MSG":"Exception occurred in VOID TRANSACTION API.",
	"LOGOUT_ERROR_CODE":"EZETAP_323030",
	"LOGOUT_ERROR_MSG":"Exception occurred in LOGOUT API.",
	"INITIALIZATION_ERROR_CODE":"EZETAP_323024",
	"INITIALIZATION_ERROR_MSG":"Exception occurred in INITIALIZE API."
}